name: flutter_selectext
description: Selectable text widget and able to set custom selection control.
version: 0.1.0
author: KNightING <knighting.dev@gmail.com>
homepage: https://github.com/KNightING/flutter_selectext

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.2.1 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter